[features]
seeds = false
skip-lint = false
[programs.localnet]
crowd_founding = "C71tuCNPkeoPXqVQcrt2EokX3V1KwiSDGD5nmWjCDqJV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/danil_sitdikov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
